-- GENERATED by backend/scripts/extract_schema.py from docs/database.md — do not edit by hand.

-- ===== 10.2 Grants (docs/database.md) =====

REVOKE ALL ON ALL TABLES IN SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO am_app, am_worker, am_readonly, am_audit_reader;

-- default: read/insert/update for the application
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO am_app, am_worker;

-- append-only tables: INSERT + SELECT only (C5) — trigger is the second lock
REVOKE UPDATE, DELETE ON health_record_entries, entry_vitals, entry_symptoms, entry_risk_flags,
       case_events, incentive_ledger, consents, audit_log FROM am_app, am_worker;
REVOKE SELECT ON audit_log FROM am_app, am_worker;   -- the app writes the audit trail but cannot read it back;
                                                     -- "who looked at my record" goes through patient_access_history() below

-- reference data is edited by admins through the app, never deleted
GRANT DELETE ON facility_capabilities, case_needed_capabilities, care_plan_items TO am_app;
GRANT DELETE ON sync_changes, idempotency_keys, otp_challenges TO am_worker;   -- retention jobs

-- analytics: no encrypted/hashed columns ever (MV grants run after §19.2 creates them)
GRANT SELECT ON v_open_cases, v_facility_live, mv_district_daily_kpis, mv_facility_response_stats TO am_readonly;
GRANT SELECT (id, type, channel, district_code, village_id, emergency_category, status, status_changed_at,
              current_facility_id, location_source, escalation_level, verified, created_at, accepted_at,
              arrived_at, closed_at) ON cases TO am_readonly;
GRANT SELECT (case_id, action, from_status, to_status, actor_role, channel, occurred_at) ON case_events TO am_readonly;

-- patient-facing audit view through a narrow function (UI §6.5)
CREATE FUNCTION patient_access_history(p_patient uuid, p_limit int DEFAULT 50)
RETURNS TABLE (occurred_at timestamptz, actor_role user_role, action text, purpose text)
LANGUAGE sql SECURITY DEFINER SET search_path = public AS $$
  SELECT occurred_at, actor_role, action, purpose FROM audit_log
  WHERE patient_id = p_patient AND action LIKE 'patient.%'
  ORDER BY occurred_at DESC LIMIT least(p_limit, 200);
$$;
REVOKE ALL ON FUNCTION patient_access_history FROM PUBLIC;
GRANT EXECUTE ON FUNCTION patient_access_history TO am_app;
