/**
 * API client (API-Guide §16.2, FR-W02, SEC-WEB-03).
 * - Access token lives in memory only; the refresh token is an HttpOnly cookie sent only to /auth/refresh
 *   together with the X-CSRF-Token header (double-submit of the non-HttpOnly `am_csrf` cookie).
 * - Every POST/PATCH carries an Idempotency-Key (API-Guide §2.5); callers pass one to make retries safe.
 * - Errors are RFC 9457 problem+json; clients switch on `code`, never on text.
 * Types come from the OpenAPI contract (`lib/api/schema.d.ts`, generated by `npm run gen:api`).
 */
import type { components } from './api/schema';
import { uuidv7 } from './uuid';

export type Schemas = components['schemas'];
export type CaseOut = Schemas['CaseOut'];
export type CaseDetail = Schemas['CaseDetailOut'];
export type Facility = Schemas['FacilityOut'];
export type FacilityOffer = Schemas['FacilityOfferOut'];
export type TransportLeg = Schemas['TransportLegOut'];
export type User = Schemas['UserOut'];
export type MatchResponse = Schemas['MatchResponse'];

export const API = process.env.NEXT_PUBLIC_API_BASE || '/api/v1';

export class ProblemError extends Error {
  constructor(
    public status: number,
    public code: string,
    public title: string,
    public detail: string | null,
    public current: unknown,
    public fields: { path: string; code: string }[] | null,
  ) {
    super(title);
  }
}

let accessToken: string | null = null;
let refreshing: Promise<boolean> | null = null;
let onSignedOut: (() => void) | null = null;
let lang = 'en';

export const tokenStore = {
  set(t: string | null) {
    accessToken = t;
  },
  get() {
    return accessToken;
  },
  onSignedOut(fn: () => void) {
    onSignedOut = fn;
  },
  setLang(l: string) {
    lang = l;
  },
};

function cookie(name: string): string | null {
  const m = document.cookie.match(new RegExp(`(?:^|; )${name}=([^;]*)`));
  return m ? decodeURIComponent(m[1]) : null;
}

export function deviceId(): string {
  try {
    let id = localStorage.getItem('am_device_id');
    if (!id) {
      id = uuidv7();
      localStorage.setItem('am_device_id', id);
    }
    return id;
  } catch {
    return uuidv7();
  }
}

/** Rotate the refresh cookie and obtain a new in-memory access token. */
export async function refreshSession(): Promise<{ accessToken: string; user: User } | null> {
  const csrf = cookie('am_csrf');
  if (!csrf) return null;
  const r = await fetch(`${API}/auth/refresh`, {
    method: 'POST',
    credentials: 'same-origin',
    headers: { 'X-CSRF-Token': csrf, 'Content-Type': 'application/json' },
    body: 'null',
  });
  if (!r.ok) return null;
  const data = await r.json();
  accessToken = data.accessToken;
  return { accessToken: data.accessToken, user: data.user };
}

async function refreshOnce(): Promise<boolean> {
  if (!refreshing) {
    refreshing = refreshSession()
      .then((x) => !!x)
      .finally(() => {
        refreshing = null;
      });
  }
  return refreshing;
}

type Opts = { method?: string; body?: unknown; idem?: string; headers?: Record<string, string>; retry?: boolean };

export async function api<T = unknown>(path: string, opts: Opts = {}): Promise<T> {
  const method = opts.method ?? (opts.body !== undefined ? 'POST' : 'GET');
  const headers: Record<string, string> = {
    Accept: 'application/json',
    'Accept-Language': lang,
    'X-Request-Id': crypto.randomUUID(),
    ...(opts.headers ?? {}),
  };
  if (accessToken) headers.Authorization = `Bearer ${accessToken}`;
  if (opts.body !== undefined) headers['Content-Type'] = 'application/json';
  if (method === 'POST' || method === 'PATCH') headers['Idempotency-Key'] = opts.idem ?? uuidv7();
  const res = await fetch(`${API}${path}`, {
    method,
    headers,
    credentials: 'same-origin',
    body: opts.body !== undefined ? JSON.stringify(opts.body) : undefined,
    cache: 'no-store',
  });
  if (res.status === 204) return undefined as T;
  const text = await res.text();
  const data = text ? JSON.parse(text) : null;
  if (!res.ok) {
    const p = data ?? {};
    if (res.status === 401 && opts.retry !== false && (p.code === 'TOKEN_EXPIRED' || p.code === 'UNAUTHENTICATED')) {
      if (await refreshOnce()) return api<T>(path, { ...opts, idem: headers['Idempotency-Key'], retry: false });
      onSignedOut?.();
    }
    throw new ProblemError(res.status, p.code ?? 'INTERNAL', p.title ?? res.statusText, p.detail ?? null, p.current ?? null,
      p.fields ?? null);
  }
  return data as T;
}
