"""Extract the PostgreSQL DDL verbatim from docs/database.md.

database.md §13 fixes the order of the initial migration:
    §5.0 → §5.14, then the §7 state-machine seed + trigger, §19.2 materialized
    views (the §10.2 grants reference them), §10.2 grants.
The seed data of §11 is written separately (migrations/sql/0003_seed_reference.sql)
because §11 is given as tables, not SQL.

Nothing in the DDL is retyped by hand: the blocks are copied from the spec so the
database is exactly what the design document says. Run from backend/:

    python scripts/extract_schema.py
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SPEC = ROOT / "docs" / "database.md"
OUT_SCHEMA = ROOT / "backend" / "migrations" / "sql" / "0001_schema.sql"
OUT_GRANTS = ROOT / "backend" / "migrations" / "sql" / "0001_grants.sql"

# Section headings, in migration order (database.md §13).
SCHEMA_SECTIONS = [
    "### 5.0 Extensions, helper functions",
    "### 5.1 Geography",
    "### 5.2 Catalogs and configuration",
    "### 5.3 Facilities",
    "### 5.4 Identity and access",
    "### 5.5 Households, patients and the village resource graph",
    "### 5.6 Privacy and consent (DPDP Act 2023)",
    "### 5.6.1 Subject keys (crypto-shredding)",
    "### 5.7 Routine care — longitudinal record, screening, teleconsultation",
    "### 5.8 Referral — cases, timeline, acceptance cascade, timers, escalation, arrival",
    "### 5.9 Transport — legs, custody chain, volunteer search",
    "### 5.10 Continuity — care plans, ASHA tasks, verified incentives, leaderboards",
    "### 5.11 Communications — outbound ladder and inbound SMS/IVR",
    "### 5.12 Platform — sync journal, idempotency, audit",
    "### 5.13 Views",
    "### 5.14 Deferred foreign keys, cross-table integrity and trigger wiring",
    "### 7.1 Allowed transitions (seed of `case_status_transitions`)",
    "### 7.2 Trigger",
    "### 19.2 Materialized views",
]
GRANT_SECTIONS = ["### 10.2 Grants"]


def sql_blocks_by_heading(text: str) -> dict[str, list[str]]:
    blocks: dict[str, list[str]] = {}
    heading = ""
    in_sql = False
    buf: list[str] = []
    for line in text.splitlines():
        if not in_sql and line.startswith("#"):
            heading = line.strip()
        if line.strip() == "```sql":
            in_sql, buf = True, []
            continue
        if in_sql and line.strip() == "```":
            in_sql = False
            blocks.setdefault(heading, []).append("\n".join(buf))
            continue
        if in_sql:
            buf.append(line)
    return blocks


def pick(blocks: dict[str, list[str]], wanted: list[str]) -> str:
    out: list[str] = []
    for want in wanted:
        match = [h for h in blocks if h.startswith(want)]
        if len(match) != 1:
            raise SystemExit(f"section not found exactly once: {want!r} -> {match}")
        h = match[0]
        out.append(f"-- ===== {h.lstrip('# ')} (docs/database.md) =====")
        out.extend(blocks[h])
    return "\n\n".join(out) + "\n"


def main() -> None:
    text = SPEC.read_text(encoding="utf-8")
    blocks = sql_blocks_by_heading(text)
    header = "-- GENERATED by backend/scripts/extract_schema.py from docs/database.md — do not edit by hand.\n\n"
    OUT_SCHEMA.write_text(header + pick(blocks, SCHEMA_SECTIONS), encoding="utf-8")
    OUT_GRANTS.write_text(header + pick(blocks, GRANT_SECTIONS), encoding="utf-8")
    n_tables = len(re.findall(r"^CREATE TABLE (\w+) \(", OUT_SCHEMA.read_text(), re.M))
    print(f"wrote {OUT_SCHEMA.name} ({n_tables} CREATE TABLE incl. partitions) and {OUT_GRANTS.name}")


if __name__ == "__main__":
    main()
