"""Create LOCAL/DEMO env files with fresh random secrets: infra/.env (compose) and backend/.env (host runs/tests).

    cd backend && uv run python scripts/setup_local_env.py [--force]

Never for staging/prod — those secrets come from Vault/KMS (SEC-INF-09). Refuses to overwrite existing files
unless --force (overwriting the KEK makes already-encrypted local data unreadable).
"""

from __future__ import annotations

import base64
import os
import secrets
import sys
from pathlib import Path

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

ROOT = Path(__file__).resolve().parents[2]
HEADER = "# LOCAL/DEMO ONLY — generated by setup; never commit. Staging/prod secrets come from Vault (SEC-INF-09).\n"


def _pw() -> str:
    return secrets.token_urlsafe(24)


def main() -> None:
    force = "--force" in sys.argv
    targets = [ROOT / "infra" / ".env", ROOT / "backend" / ".env"]
    if not force and any(p.exists() for p in targets):
        sys.exit("env files already exist — pass --force to regenerate (local encrypted data becomes unreadable)")
    jwt_key = Ed25519PrivateKey.generate().private_bytes(
        serialization.Encoding.PEM, serialization.PrivateFormat.PKCS8, serialization.NoEncryption())
    shared = {
        "AM_ENV": "local",
        "AM_DB_OWNER_PASSWORD": _pw(),
        "AM_DB_APP_PASSWORD": _pw(),
        "AM_DB_WORKER_PASSWORD": _pw(),
        "AM_RABBIT_PASSWORD": _pw(),
        "AM_S3_ACCESS_KEY": secrets.token_hex(10),
        "AM_S3_SECRET_KEY": _pw(),
        "AM_S3_PUBLIC_ENDPOINT": "http://localhost:9000",
        "AM_WEB_ORIGIN": "http://localhost:8080",
        "AM_API_BASE_URL": "http://localhost:8080",
        "AM_KEK_B64": base64.b64encode(os.urandom(32)).decode(),
        "AM_HMAC_KEY_B64": base64.b64encode(os.urandom(32)).decode(),
        "AM_JWT_PRIVATE_KEY_PEM_B64": base64.b64encode(jwt_key).decode(),
        "AM_TURN_SECRET": base64.urlsafe_b64encode(os.urandom(24)).decode(),
        "AM_REDIS_PASSWORD": _pw(),
    }
    infra = dict(shared)
    # host processes (pytest, seed, `next dev` on :3000) reach the compose data stores via 127.0.0.1 ports
    host = {k: v for k, v in shared.items() if k != "AM_REDIS_PASSWORD"}
    host.update({
        "AM_DB_HOST": "localhost",
        "AM_REDIS_URL": f"redis://:{shared['AM_REDIS_PASSWORD']}@localhost:6379/0",
        "AM_AMQP_URL": f"amqp://am:{shared['AM_RABBIT_PASSWORD']}@localhost:5672/aapatmitra",
        "AM_S3_ENDPOINT": "http://localhost:9000",
        "AM_WEB_ORIGIN": "http://localhost:3000",
    })
    for path, values in ((targets[0], infra), (targets[1], host)):
        path.write_text(HEADER + "".join(f"{k}={v}\n" for k, v in values.items()))
        path.chmod(0o600)
        print(f"wrote {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
