-keepattributes *Annotation*, InnerClasses, Signature
-keep class net.zetetic.database.** { *; }
-keepclassmembers class kotlinx.serialization.json.** { *** Companion; }
-keep,includedescriptorclasses class in.aapatmitra.**$$serializer { *; }
-assumenosideeffects class android.util.Log { public static *** d(...); public static *** v(...); public static *** i(...); }
