"""12-factor configuration (TRD §3.2 pydantic-settings).

Secrets come from the environment (Vault / cloud secret manager in staging and prod —
SEC-INF-09). Nothing secret has a usable default outside `local`.
"""

from __future__ import annotations

from functools import cached_property
from typing import Literal

from pydantic import Field, model_validator
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_prefix="AM_", env_file=".env", extra="ignore")

    env: Literal["local", "demo", "test", "staging", "prod"] = "local"
    api_base_url: str = "http://localhost:8000"
    jwt_issuer: str = "https://api.aapatmitra.in"
    jwt_audience: str = "aapatmitra-api"
    web_origin: str = "http://localhost:3000"  # SEC-API-09: CORS allows only the console origin

    # PostgreSQL — per-service roles (database.md §10.1)
    db_host: str = "localhost"
    db_port: int = 5432
    db_name: str = "aapatmitra"
    db_owner_user: str = "postgres"
    db_owner_password: str = "postgres"  # noqa: S105 - local only; rejected outside local/test
    db_app_password: str = "am_app_local"  # noqa: S105 - local only; rejected outside local/test
    db_worker_password: str = "am_worker_local"  # noqa: S105 - local only; rejected outside local/test

    redis_url: str = "redis://localhost:6379/0"
    amqp_url: str = "amqp://guest:guest@localhost:5672//"
    # run background tasks in-process after commit instead of through Celery (tests, single-box demo)
    inline_tasks: bool = False

    # Keys (base64). Local-only defaults are generated by scripts/gen_keys.py into .env.
    kek_b64: str = ""                 # stand-in for the Vault Transit KEK (database.md §20)
    kek_id: str = "local:kek#1"
    hmac_key_b64: str = ""            # blind-index key (SEC-CRY-04); versioned
    hmac_key_version: int = 1
    jwt_private_key_pem_b64: str = ""  # Ed25519 (SEC-ID-05, EdDSA)
    jwt_kid: str = "local-1"
    turn_secret: str = "local-turn-secret"  # noqa: S105 - local only; rejected outside local/test
    turn_urls: list[str] = Field(default_factory=lambda: ["turn:localhost:3478?transport=udp",
                                                          "turns:localhost:443?transport=tcp"])

    # Channels (TRD §3.5 adapters)
    sms_provider: Literal["fake", "exotel", "twilio"] = "fake"
    push_provider: Literal["fake", "fcm"] = "fake"
    router_provider: Literal["haversine", "osrm"] = "haversine"
    osrm_url: str = "http://osrm:5000"
    twilio_auth_token: str = ""
    exotel_webhook_user: str = ""
    exotel_webhook_password: str = ""
    exotel_webhook_path_secret: str = ""
    helpline_number: str = "108"

    # Object storage (database.md Part E)
    s3_endpoint: str = "http://localhost:9000"
    s3_public_endpoint: str = "http://localhost:9000"
    s3_access_key: str = "minioadmin"
    s3_secret_key: str = "minioadmin"  # noqa: S105 - local only; rejected outside local/test
    s3_region: str = "ap-south-1"

    min_android_version: str = "1.0.0+1"  # API-Guide §6.14 /version minAndroidVersion

    access_token_ttl_s: int = 15 * 60
    refresh_ttl_android_s: int = 30 * 24 * 3600
    refresh_ttl_web_s: int = 12 * 3600
    refresh_ttl_admin_web_s: int = 8 * 3600

    @model_validator(mode="after")
    def _no_default_secrets_outside_local(self) -> Settings:
        """SEC-INF-09: staging/demo/prod must load every secret from Vault / the secret manager."""
        if self.env in ("local", "test"):
            return self
        defaults = {"db_owner_password": "postgres", "db_app_password": "am_app_local",  # noqa: S105
                    "db_worker_password": "am_worker_local", "turn_secret": "local-turn-secret",  # noqa: S105
                    "s3_secret_key": "minioadmin"}  # noqa: S105
        bad = [k for k, v in defaults.items() if getattr(self, k) == v]
        if not self.kek_b64 or not self.hmac_key_b64 or not self.jwt_private_key_pem_b64:
            bad.append("key material")
        if bad:
            raise ValueError(f"refusing to start '{self.env}' with default/missing secrets: {bad}")
        return self

    @property
    def dev_routes_enabled(self) -> bool:
        # API-Guide §17: /dev/* routes exist only in local and demo
        return self.env in ("local", "demo", "test")

    @property
    def docs_enabled(self) -> bool:
        # API-Guide §1.2 / SEC-API-04: /docs open in local/demo, disabled in prod
        return self.env in ("local", "demo", "test")

    @cached_property
    def redis_prefix(self) -> str:
        return f"am:{self.env}:"  # database.md §15.1 R4

    def _dsn(self, driver: str, user: str, password: str) -> str:
        return f"postgresql+{driver}://{user}:{password}@{self.db_host}:{self.db_port}/{self.db_name}"

    @property
    def database_url_app(self) -> str:
        return self._dsn("asyncpg", "am_app", self.db_app_password)

    @property
    def database_url_worker(self) -> str:
        return self._dsn("asyncpg", "am_worker", self.db_worker_password)

    @property
    def database_url_owner_sync(self) -> str:
        return self._dsn("psycopg", self.db_owner_user, self.db_owner_password)

    def bucket(self, name: str) -> str:
        return f"am-{self.env}-{name}"


settings = Settings()
