"""Database access (TRD §3.2): async SQLAlchemy 2.0 + GeoAlchemy2, one transaction per request.

Tables are *reflected* from the migrated schema instead of re-declared as ORM classes, so the
code can never drift from database.md (the migration is the single definition). All queries use
SQLAlchemy Core expressions — parameterised, no string SQL (SEC-API-03).
"""

from __future__ import annotations

from typing import Any

import geoalchemy2  # noqa: F401  (registers geography type for reflection)
from sqlalchemy import MetaData, Table, cast, func
from sqlalchemy.ext.asyncio import AsyncConnection, AsyncEngine, create_async_engine
from sqlalchemy.sql.elements import ColumnElement

from app.core.config import settings

_engines: dict[str, AsyncEngine] = {}
metadata = MetaData()
DEFAULT_ROLE = "app"  # Celery worker processes switch this to "worker" (am_worker, database.md §10.1)


def engine(role: str | None = None) -> AsyncEngine:
    role = role or DEFAULT_ROLE
    if role not in _engines:
        url = settings.database_url_app if role == "app" else settings.database_url_worker
        _engines[role] = create_async_engine(
            url,
            pool_size=10,
            max_overflow=10,
            pool_pre_ping=True,
            connect_args={"server_settings": {"timezone": "UTC", "statement_timeout": "15000",
                                              "application_name": f"aapatmitra-{role}"}},
        )
    return _engines[role]


async def dispose_engines() -> None:
    for e in list(_engines.values()):
        await e.dispose()
    _engines.clear()


class _Tables:
    """Attribute access to reflected tables: `T.cases`, `T.facility_offers`, ..."""

    def __getattr__(self, name: str) -> Table:
        try:
            return metadata.tables[name]
        except KeyError as exc:  # pragma: no cover - programming error
            raise AttributeError(f"table {name!r} not reflected") from exc


T = _Tables()


async def reflect(role: str | None = None) -> None:
    if metadata.tables:
        return
    from sqlalchemy import String
    from sqlalchemy.dialects.postgresql.base import ischema_names

    ischema_names.setdefault("xid8", String)  # sync_changes.txid — only ever read through the §9.2 SQL
    async with engine(role).connect() as conn:
        await conn.run_sync(lambda sync: metadata.reflect(bind=sync, views=True))
    # am_app/am_worker may INSERT but not SELECT audit_log (database.md §10.2), so no implicit RETURNING
    # and the identity value is generated by PostgreSQL (GENERATED ALWAYS) — never pre-fetched by SQLAlchemy.
    for name, col in (("audit_log", "id"), ("sync_changes", "seq")):
        table = metadata.tables[name]
        table.implicit_returning = False
        table.c[col].autoincrement = False
        table.c[col].identity = None
        table.c[col].server_default = None
        table.c[col].nullable = True  # client-side only: the column is filled by the database


# ---------- geography helpers (GeoJSON lat/lng in, WGS84 geography out) ----------

def point(lat: float, lng: float) -> ColumnElement[Any]:
    return cast(func.ST_SetSRID(func.ST_MakePoint(lng, lat), 4326), geoalchemy2.Geography("POINT", 4326))


def lat_of(col: Any) -> ColumnElement[Any]:
    return func.ST_Y(cast(col, geoalchemy2.Geometry))


def lng_of(col: Any) -> ColumnElement[Any]:
    return func.ST_X(cast(col, geoalchemy2.Geometry))


def geo_point(row: Any, prefix: str) -> dict[str, float] | None:
    lat, lng = getattr(row, f"{prefix}_lat", None), getattr(row, f"{prefix}_lng", None)
    if lat is None or lng is None:
        return None
    return {"lat": round(float(lat), 6), "lng": round(float(lng), 6)}


Conn = AsyncConnection
